global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: /actuator/prometheus
    scheme: https
    static_configs:
      - targets: ['euics.co.kr']

  - job_name: 'node-exporter'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['52.79.166.144:9100']